# Generated by Django 3.2.3 on 2021-07-22 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210722_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cameras',
            new_name='Camera',
        ),
        migrations.RenameModel(
            old_name='Frames',
            new_name='Frame',
        ),
    ]
